In [1]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [2]:
# 1D array
arr1 = np.array([1, 2, 3])
print("1D Array:", arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 2))
print("Ones Array:\n", ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print("Range Array:", range_arr)

# Array with equally spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

# Random array
random_arr = np.random.rand(3, 3)  # Uniform distribution
print("Random Array:\n", random_arr)


1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.20862537 0.05008008 0.60450592]
 [0.15058016 0.29360468 0.73718961]
 [0.19184243 0.98138688 0.86458117]]


In [3]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((3, 2))
print("Reshaped Array:\n", reshaped)

# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [7]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933


### Some assignment problems

In [10]:
# Assignment 1
'''
Create an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.
Then reshape it to a (9, 2) array and take its transpose. 
Find the locations where all elements are greater than the mean of the array and print it
'''

'\nCreate an array of 18 random elements of shape (3, 6) and add the array [0, 0, 2, 4, 5, 3] to each row.\nThen reshape it to a (9, 2) array and take its transpose. \nFind the locations where all elements are greater than the mean of the array and print it\n'

In [8]:
import numpy as np

# random array of shape (3, 6)
arr = np.random.rand(3, 6) 
print("Original Array:\n", arr)

# Adding the given array to each row (broadcasting)
add_array = np.array([0, 0, 2, 4, 5, 3])
arr_added = arr + add_array

# Reshape to (9, 2)
reshaped = arr_added.reshape(9, 2)

# Take transpose
transposed = reshaped.T

# Compute mean of the array
mean_value = transposed.mean()

# Find locations where all elements are greater than the mean
locations = np.column_stack((rows, cols)).astype(int)

# Print results
print("\nFinal Transposed Array:\n", transposed)
print("\nMean of the array:", mean_value)
print("\nLocations where elements > mean:")
print(locations)


Original Array:
 [[0.34770062 0.69056876 0.63298788 0.72461863 0.57826578 0.8069127 ]
 [0.45033566 0.03289173 0.77407371 0.42345511 0.44681976 0.47998628]
 [0.44211739 0.90600421 0.21204738 0.49047332 0.1115981  0.47525292]]

Final Transposed Array:
 [[0.34770062 2.63298788 5.57826578 0.45033566 2.77407371 5.44681976
  0.44211739 2.21204738 5.1115981 ]
 [0.69056876 4.72461863 3.8069127  0.03289173 4.42345511 3.47998628
  0.90600421 4.49047332 3.47525292]]

Mean of the array: 2.8347838859049688

Locations where elements > mean:
[[0 2]
 [0 5]
 [0 8]
 [1 1]
 [1 2]
 [1 4]
 [1 5]
 [1 7]
 [1 8]]


In [12]:
# Assignment 2
'''
Create an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation
(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)
'''

'\nCreate an array of length 20 that models a poisson distribution and center it around the mean and normalise it by dividing it by the standard deviation\n(Centering around some value "a" is subtracting "a" from each element and normalising is to divide it by some factor)\n'

In [9]:
import numpy as np

# Poisson-distributed array of length 20
poisson_arr = np.random.poisson(lam=5, size=20)

# Compute mean and standard deviation
mean_val = poisson_arr.mean()
std_val = poisson_arr.std()

# Center the array around the mean
centered = poisson_arr - mean_val

# Normalize by dividing by the standard deviation
normalized = centered / std_val

# Print results
print("Original Poisson Array:")
print(poisson_arr)

print("\nMean:", mean_val)
print("Standard Deviation:", std_val)

print("\nCentered Array (x - mean):")
print(centered)

print("\nCentered and Normalized Array:")
print(normalized)


Original Poisson Array:
[ 2  7  2  2  7  3  3  6  2  5  6  7  8  8  3  6  5  2  5 10]

Mean: 4.95
Standard Deviation: 2.3973944189473704

Centered Array (x - mean):
[-2.95  2.05 -2.95 -2.95  2.05 -1.95 -1.95  1.05 -2.95  0.05  1.05  2.05
  3.05  3.05 -1.95  1.05  0.05 -2.95  0.05  5.05]

Centered and Normalized Array:
[-1.23050257  0.85509501 -1.23050257 -1.23050257  0.85509501 -0.81338306
 -0.81338306  0.43797549 -1.23050257  0.02085598  0.43797549  0.85509501
  1.27221452  1.27221452 -0.81338306  0.43797549  0.02085598 -1.23050257
  0.02085598  2.10645356]
